{{- range .Values.gateways }}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  # The selector matches the ingress gateway pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .port.number }}
        name: {{ .port.name }}
        protocol: {{ .port.protocol }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote}}
        {{- end}}
{{- end}}