package main

import (
	"fmt"
	"log"

	// docs are generated by Swag CLI, you have to import them.
	// replace with your own docs folder, usually "github.com/username/reponame/docs"
	_ "github.com/ggorockee/working_with_microservice_in_go/cmd/api/docs"
	"github.com/ggorockee/working_with_microservice_in_go/cmd/api/routes"
)

const PORT = 3000

// @title Campint Application
// @version 1.0
// @description This is an API for Book Application

// @contact.name ggorockee
// @contact.email ggorockee@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /v1
func main() {
	app := routes.New()
	log.Fatal(app.Listen(fmt.Sprintf(":%d", PORT)))
}
