apiVersion: v1
kind: Service
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: TCP
      name: {{ .portName }}
    {{- end}}
  selector:
    {{- include "broker.selectorLabels" . | nindent 4 }}
